import streamlit as st
import os
from main import run_neuro_bridge

st.set_page_config(page_title="NeuroBridge AI", page_icon="🧠", layout="wide")

st.title("🧠 NeuroBridge: The Oncology Agentic OS")
st.markdown("---")

# Sidebar for Patient Context
with st.sidebar:
    st.header("Patient Profile")
    patient_name = st.text_input("Name", "John Doe")
    age = st.number_input("Age", 45)
    st.info("OnDemand Agents Active: 6/6")

# Main Interface: MRI Upload
st.header("1. Diagnostic Input")
uploaded_file = st.file_uploader("Upload 3D MRI (DICOM)", type=["dcm"])

if uploaded_file:
    # Save temp file
    temp_path = f"data/{uploaded_file.name}"
    with open(temp_path, "wb") as f:
        f.write(uploaded_file.getbuffer())
    
    with st.spinner("Agentic Swarm processing scan..."):
        # Trigger the full workflow from main.py
        results = run_neuro_bridge(temp_path)
    
    # Display Results
    col1, col2 = st.columns(2)
    with col1:
        st.success("✅ Radiology Agent: Tumor Detected")
        st.json({"Margins": "Clear", "Type": "Grade II Glioma", "Location": "Frontal Lobe"})
    
    with col2:
        st.warning("⚠️ Pharmacy Agent: Safety Check")
        st.write(results) # The medication schedule generated by MedGemma 27B

st.markdown("---")
st.caption("Powered by MedGemma 1.5 & OnDemand AI OS")
